apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  annotations:
    kubernetes.io/change-cause: "release v1.0.0-stable"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: nginx:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
